twist_mux:
  ros__parameters:

    use_stamped: true

    topics:
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 90
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      nav2:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 70
        