twist_mux:
  ros__parameters:

    # use_stamped: true
    use_stamped: false

    topics:
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 90
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      nav2:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 70
      watchdog:
          topic: cmd_vel_watchdog
          timeout: 0.0 # 워치독은 타임아웃 없이 
          priority: 10
        